# Generated by Django 4.2.1 on 2023-06-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColinaDoSol', '0002_alter_store_business_alter_store_store_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ColinaDoSol.business'),
        ),
    ]
