# Generated by Django 4.2.2 on 2023-06-22 21:40

import ColinaDoSol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColinaDoSol', '0004_alter_operatinghours_lunch_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='ColinaDoSol/img/LogoCoresH.png', upload_to='ColinaDoSol/img/')),
                ('description', models.TextField(default='Galeria de lojas localizada em Alfornelos, no concelho da Amadora, construído em 1992. Tem 61 lojas e parque de estacionamento.')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images')),
                ('caption', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to=ColinaDoSol.models.get_image_path),
        ),
    ]
