# Generated by Django 4.2.2 on 2023-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColinaDoSol', '0006_siteconfiguration_facebooklink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(upload_to='content/ColinaDoSol/img/'),
        ),
    ]
