# Generated by Django 4.2.2 on 2023-06-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ColinaDoSol', '0007_alter_siteconfiguration_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
