# Generated by Django 4.2.2 on 2023-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColinaDoSol', '0010_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(verbose_name='Descrição da loja'),
        ),
    ]
